# Generated by Django 5.1.7 on 2025-04-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.register_table')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.band')),
            ],
        ),
    ]
