# Generated by Django 5.1.7 on 2025-04-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_carttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
